name: Compilación de la rama main

on:
  push:
    branches:
      - "main"
      - "feature/Integracion-Continua"
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345

    steps:
      # Clona el repositorio
      - name: Check out repository
        uses: actions/checkout@v3

      # Configura Java 8
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8' # Usa '8' en lugar de '1.8'
          distribution: 'temurin'
          cache: maven
      
      # Set up PostgreSQL
      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      # Ejecutar el script SQL para crear la base de datos y las tablas
      - name: Execute SQL script to set up User database
        run: |
          # Establecer la contraseña del usuario postgres
          export PGPASSWORD=12345
          # Ejecutar el script SQL para crear las tablas
          psql -h localhost -U postgres -f User.sql
      
      - name: Execute SQL script to set up Content database
        run: |
          # Establecer la contraseña del usuario postgres
          export PGPASSWORD=12345
          # Ejecutar el script SQL para crear las tablas
          psql -h localhost -U postgres -f Content.sql

      - name: Execute SQL script to set up Visualization database
        run: |
          # Establecer la contraseña del usuario postgres
          export PGPASSWORD=12345
          # Ejecutar el script SQL para crear las tablas
          psql -h localhost -U postgres -f Visualization.sql

      # Construye y prueba el primer microservicio
      - name: Build and test microservicio Visualization 
        run: |
          cd Visualization
          mvn clean install
          mvn test

      # Construye y prueba el segundo microservicio
      - name: Build and test microservicio Content
        run: |
          cd Content
          mvn clean install
          mvn test

      # Construye y prueba el tercer microservicio
      - name: Build and test microservicio User
        run: |
          cd User
          mvn clean install
          mvn test
          
      - name: Run Visualization microservice
        run: |
          cd Visualization
          mvn spring-boot:run &

      - name: Run Content microservice
        run: |
          cd Content
          mvn spring-boot:run &
      - name: Run User microservice
        run: |
          cd User
          mvn spring-boot:run &  
                
      # Paso 5: Instalar Node.js (para usar Newman)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Paso 6: Instalar Newman
      - name: Install Newman
        run: npm install -g newman

      # Paso 7: Ejecutar pruebas de Postman
      - name: Run Postman User tests
        run: newman run tests/User.postman_collection.json
      
      - name: Run Postman Content tests
        run: newman run tests/Content.postman_collection.json
      
      - name: Run Postman Visualization tests
        run: newman run tests/Visualization.postman_collection.json
      
      - name: Run a one-line script
        run: echo Todos los microservicios \(Visualization, User, Content\) han sido compilados y probados exitosamente

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Cambia según la versión que uses

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
